version: "3"
services:
  db:
    image: mysql:8.0.33
    volumes:
      - lypa-mysql-data:/var/lib/mysql
      - ./initTables.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE:
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3306:3306"
    networks:
      - lypa-network
  web:
    build:
      context: ./LypaFront
      dockerfile: Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=
    ports:
      - "3000:3000"
    networks:
      - lypa-network
    depends_on:
      - back
  back:
    build:
      context: ./LypaBack
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_USERNAME=
      - DB_PASSWORD=
      - DB_DATABASE=
      - TG_TOKEN=
    ports:
      - "8000:8000"
    networks:
      - lypa-network
    depends_on:
      - db    
volumes:
  lypa-mysql-data:
networks:
  lypa-network:  