ALTER USER 'root' IDENTIFIED WITH mysql_native_password BY 'password';

CREATE TABLE TASKS (
  id INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(255),
  Description VARCHAR(255)
);

CREATE TABLE USERS (
  id INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(255),
  TgID INT
);

CREATE TABLE RESULTS (
  id INT PRIMARY KEY AUTO_INCREMENT,
  TaskID INT NOT NULL,
  UserID INT NOT NULL,
  Score INT,
  FOREIGN KEY (TaskID) REFERENCES TASKS(id),
  FOREIGN KEY (UserID) REFERENCES USERS(id)
);